- name: Execute whoami and pwd commands on remote server
  hosts: 1.1.1.45
  tasks:
    - name: Run whoami command
      command: whoami
      register: whoami_output

    - name: Print whoami output
      debug:
        var: whoami_output.stdout

    - name: Run pwd command
      command: pwd
      register: pwd_output

    - name: Print pwd output
      debug:
        var: pwd_output.stdout
