---
- name: Execute whoami and pwd commands on remote server
  hosts: all
  tasks:
    - name: Run whoami command
      command: whoami
      register: whoami_output

    - name: Print whoami output
      debug:
        msg: "Whoami output: {{ whoami_output.stdout }}"

    - name: Run pwd command
      command: pwd
      register: pwd_output

    - name: Print pwd output
      debug:
        msg: "Pwd output: {{ pwd_output.stdout }}"
