- name: Execute whoami and pwd commands on remote server
  hosts: 1.1.1.45
  tasks:
    - name: Run shell commands
      shell: |
        echo "Current directory: $(pwd)"
        echo "Executing user: $(whoami)"
    - name: Run whoami command
      command: whoami
      register: whoami_output

    - name: Print whoami output
      shell: echo "{{ whoami_output.stdout }}"
      register: whoami_echo_output

    - name: Print whoami echo output
      debug:
        var: whoami_echo_output.stdout

    - name: Run pwd command
      command: pwd
      register: pwd_output

    - name: Print pwd output
      shell: echo "{{ pwd_output.stdout }}"
      register: pwd_echo_output

    - name: Print pwd echo output
      debug:
        var: pwd_echo_output.stdout
